### ISSUE TITLE
MIDI NOTE not working

### ISSUE THREAD

**Issue by edwardcolin** [ldrolez/clyphx-live11#58]
the MIDI NOTE parameter appears to be unresponsive suddenly, have tried downgrading to 2.7.4 with no change, not sure if this is Clyphx related but wondering if anyone has any fix

**Comment by edwardcolin** [comment]
i need to use MIDI NOTE because there is no action for LOOPER CLEAR. adding a way to clear the looper device would solve this issue also :)

**Comment by light2peter** [comment]
Hi, MIDI NOTE works for me on Live 11.3.25 / Clyphx 2.7.5 / Windows 10...

The one thing is that I had to run loopmidi to create a loopback device, and configure clyphx to output midi there, since the MIDI NOTE command doesn't route notes back into ableton.

If that fixes your issue maybe the command docs should be updated.

**Comment by edwardcolin** [comment]
thank you! i believe that i had to use loopback to get it working last time now that you mention it and that is probably my problem. thanks again :)
